### ISSUE TITLE
возможная опечатка

### ISSUE THREAD

**Issue by mavriq** [kazenniy/atapt#1]
В методе readSmart класса atapt есть следующие строки
https://github.com/kazenniy/atapt/blob/master/atapt/atapt.py#L506
```python
            aid = int.from_bytes(buf[2 + i * 12], byteorder='little')
            pre_fail = int.from_bytes(buf[2 + i * 12 + 1], byteorder='little') & 1
            online = (int.from_bytes(buf[2 + i * 12 + 1], byteorder='little') & 2) >> 1
            current = int.from_bytes(buf[2 + i * 12 + 3], byteorder='little')
```
для переменных `pre_fail` и `online` используется одно и то же смещение. выглядят эти строки выбивающимися из общего тренда
возможно, я неправ, код `... & 2) >> 1` наводит меня на такие мысли.
но все-же решил уточнить у вас - нет ли тут опечатки?

**Comment by kazenniy** [comment]
Тут нет ошибки. Смещение одинаковое потому, что атрибуты pre_fail и online хранятся в одном двухбайтовом слове. За атрибут pre_fail отвечает бит 0, за атрибут online бит 1. Бит 1 после извлечения сдвигается вправо, чтобы значение результирующей переменной было 1/0 а не 2/0.

**Comment by mavriq** [comment]
спасибо, я тоже так предположил, но решил окончательно развеять сомнения
