### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by altelan** [kazenniy/atapt#7]
OS: ArchLinux
Python: 3.6

I get a "Segmentation fault" error, with this code:

```python
from atapt import atapt

disk0 = atapt.atapt("/dev/sda")
disk1 = atapt.atapt("/dev/sdb")

print (disk0.dev, disk0.model)
print (disk1.dev, disk1.model)

```

return:

```bash
/dev/sda VBOX HARDDISK
/dev/sdb VBOX HARDDISK
Segmentation fault
```

**Comment by kazenniy** [comment]
It is not for virtual disks. It is for real HDD only.

**Comment by altelan** [comment]
With one disk, this works well, if more, error, in what could be the problem?

**Comment by altelan** [comment]
I tried with physical disks, the error was repeated

**Comment by altelan** [comment]
library will work on python 3.5.4
